# Generated by Django 6.0.4 on 2026-08-28 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_study_status'),
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('user',), name='unique_active_session_per_user'),
        ),
    ]
