"""
URL patterns for the academics app.
Mounted at /api/v1/academics/ via notiva/api_urls.py.

Routes generated by DefaultRouter:
    GET    /semesters/
    POST   /semesters/
    GET    /semesters/{id}/
    PUT    /semesters/{id}/
    PATCH  /semesters/{id}/
    DELETE /semesters/{id}/

    (same pattern for /subjects/ and /notebooks/)
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import SemesterViewSet, SubjectViewSet, NotebookViewSet

router = DefaultRouter()
router.register(r'semesters', SemesterViewSet, basename='semester')
router.register(r'subjects', SubjectViewSet, basename='subject')
router.register(r'notebooks', NotebookViewSet, basename='notebook')

urlpatterns = [
    path('', include(router.urls)),
]
