# Generated by Django 6.0.4 on 2026-08-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_difficulty_note_estimated_read_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteattachment',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
