# Generated by Django 6.0.4 on 2026-08-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_noteattachment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='study_status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], max_length=20, null=True),
        ),
    ]
